"""Add logistics and inventory schema fixes

Revision ID: 24b7236fc10c
Revises: 356678061503
Create Date: 2026-07-08 21:50:50.088108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b7236fc10c'
down_revision: Union[str, None] = '356678061503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('optimal_temperature', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('optimal_humidity', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('status', sa.String(), nullable=True))
    op.add_column('inventory', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('shipments', sa.Column('shipment_id', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('quantity_kg', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('estimated_arrival', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_shipments_shipment_id'), 'shipments', ['shipment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_shipment_id'), table_name='shipments')
    op.drop_column('shipments', 'estimated_arrival')
    op.drop_column('shipments', 'quantity_kg')
    op.drop_column('shipments', 'shipment_id')
    op.drop_column('inventory', 'last_updated')
    op.drop_column('inventory', 'status')
    op.drop_column('inventory', 'optimal_humidity')
    op.drop_column('inventory', 'optimal_temperature')
    # ### end Alembic commands ###
