"""Initial migration

Revision ID: 356678061503
Revises: 
Create Date: 2026-07-08 09:50:36.170354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356678061503'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=True),
    sa.Column('forecast_period', sa.Date(), nullable=True),
    sa.Column('predicted_demand', sa.Float(), nullable=True),
    sa.Column('actual_demand', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_crop_name'), 'forecasts', ['crop_name'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=True),
    sa.Column('warehouse_location', sa.String(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('spoilage_rate', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_crop_name'), 'inventory', ['crop_name'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_table('sales_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=True),
    sa.Column('quantity_sold', sa.Float(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_history_crop_name'), 'sales_history', ['crop_name'], unique=False)
    op.create_index(op.f('ix_sales_history_id'), 'sales_history', ['id'], unique=False)
    op.create_index(op.f('ix_sales_history_sale_date'), 'sales_history', ['sale_date'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('dispatch_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_crop_name'), 'shipments', ['crop_name'], unique=False)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('crop_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('N', sa.Float(), nullable=True),
    sa.Column('P', sa.Float(), nullable=True),
    sa.Column('K', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('predicted_crop', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_queries_id'), 'crop_queries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_queries_id'), table_name='crop_queries')
    op.drop_table('crop_queries')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_crop_name'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_sales_history_sale_date'), table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_id'), table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_crop_name'), table_name='sales_history')
    op.drop_table('sales_history')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_crop_name'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_crop_name'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
